# Nombre de la aplicación
spring.application.name=user-management-api

#Configuración de la conexión a PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/user_management_api
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Configuración Hibernate (Traductor Java <-> SQL)
# 'update' creará las tablas automáticamente cuando definamos las entidades
spring.jpa.hibernate.ddl-auto=update
# Muestra las consultas SQL en la consola para ver qué está pasando
spring.jpa.show-sql=true
# Embellecedor para consultas SQL más legibles en consola
spring.jpa.properties.hibernate.format_sql=true
# Dialecto para que Spring hable "el idioma" específico de PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect